dataset: ogbg-moltox21

# model
num_layer: 3
readout: mean

# learning
lr: 0.001
wdecay: 0.0002
batch_size: 1024
# patience: 100

# diffusion-based augmentation
n_negative: 1
out_steps: 1
topk: 20
aug_batch: 10000
start: 20
iteration: 10
strategy: add_once
snr: 1
scale_eps: 0
perturb_ratio: 0.2

no_print: True