dataset: ogbg-molclintox

# model
epochs: 300
model: gin
readout: max

# clusters
cluster_method: 'k-mean'
pca_dim: 3
# n_clusters: 50
cut_off': 0.8
radius: 4
n_bits: 1024  

# learning
lr: 0.1
wdecay: 0.05
batch_size: 2048
patience: 30

# diffusion-based augmentation
# n_negative: 4
# out_steps: 1
# topk: 100
aug_batch: 2000
start: 20
iteration: 5
end: 300
# strategy: replace_accumulate
snr: 1
scale_eps: 0.1
perturb_ratio: 0.4

no_print: True
