dataset: ogbg-molbbbp

# model
num_layer: 2
emb_dim: 128
drop_ratio: 0.8

# learning
wdecay: 0
batch_size: 2048

# diffusion-based augmentation
n_negative: 1
out_steps: 2
topk: 30
aug_batch: 2000
start: 20
iteration: 20
strategy: add_once
snr: 0.2
scale_eps: 0
perturb_ratio: 0.02

no_print: True
