dataset: ogbg-molsider

# model
epochs: 350
model: gin
num_layer: 3

# clusters
cluster_method: 'k-mean'
pca_dim: 3
# n_clusters: 50
cut_off': 0.8
radius: 4
n_bits: 1024  

# learning
lr: 0.0002
batch_size: 2048
patience: 300

# diffusion-based augmentation
n_negative: 5
out_steps: 5
# topk: 25
aug_batch: 2048
start: 60
iteration: 10
# strategy: replace_once
snr: 1
end: 300
scale_eps: 0
perturb_ratio: 0.2

no_print: True

