dataset: ogbg-molbace

epochs: 350

# model
model: gin
num_layer: 3
readout: max
norm_layer: size_norm

# clusters
cluster_method: 'k-mean'
pca_dim: 3
# n_clusters: 50
cut_off': 0.8
radius: 4
n_bits: 1024    

# learning
lr: 0.0001
wdecay: 0.0001
batch_size: 2048
patience: 300

# diffusion-based augmentation
# n_negative: 5
# out_steps: 5
# topk: 120
aug_batch: 2048
start: 60 # no augmentation
end: 300
iteration: 10
# strategy: add_accumulate

# original:replace_accumulate
snr: 1
scale_eps: 0.
perturb_ratio: 0.02

no_print: True